name: CI

on:
  push:
    branches:
      - master

jobs:
  build_linux_static:
    name: x64-linux
    runs-on: ubuntu-22.04
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true

  build_linux_dynamic:
    name: x64-linux-dynamic
    runs-on: ubuntu-22.04
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux-dynamic
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
