name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b3e0a1e625a0cc00073efb763e39088e5b75939e
      - run: cp vcpkg-tool vcpkg/vcpkg
      - run: sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf-archive libxxf86vm-dev nasm
      - run: vcpkg install --triplet=x64-linux-release --host-triplet=x64-linux-release
      - run: tree vcpkg/buildtrees/
