name: CI

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    name: x64-linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
